apiVersion: v1
kind: Secret
metadata:
    name: otfl-github-oauth
    namespace: otfl
type: Opaque
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:5R1K5HJVXuC02/clsfrJOj23tGo=,iv:KHdQxwcAVVlRNBxUj+jN1UqYyGRT+zJdb/mmBJ1GZoY=,tag:8KLtOI4tGpOwLSNObjCKOA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:wo6iLVgz3o8YnEty93aixg+xfnZrd/l8Bad6S8Gluwi0M76PBCw+8g==,iv:7YyAoDEysrIIG4Ixe0h7J3giBZYbLBrU71MW8OhNzMw=,tag:T9gESY/R09XHTg2GoPVI0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cG90M2xMYU9ZUGdvSHJF
            M2xCcEdPL2ZudnczRENSMU9pTzNmYUpDcG44ClBHSkdqY1EzMklKRFBOSVFFV2hw
            R0hYVUwyR2tYNlhieFQyMUpBTFBzeU0KLS0tIHk1MExUYS9lbW9UV21pcHJ3TTQ0
            WkVMRWdnS1FrZnMyYmRRNm84c3pFVU0KDfZQLMDKw1WNmDMB19rH+8k9/+6A7KCP
            oH/s2UZzVct78z2E/MXGhF4FzZS2q/ZgicC+L+17Fe8yc8jtmY5Wdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gqdqq7uagezyew5uvhylgcasuntmltqx3mdxmwa6es5k393hg3ns4fsyrt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T14:17:15Z"
    mac: ENC[AES256_GCM,data:Tie1CgRLTMyGMsSjcdyEdz/Qv6RkoyZo5oxs+9TlvYYGpU/NxlUPyIFfPJarnsx5R3lwKUmDQ6Azo1nVVrRTZxNzS6J8iu7xwioOWwYm8xPECqFhRLGLe6B36aLN0QZoYC+/yt7F3/C6hvQof7/gDyd15czvBGHwVPZnARm5Ly8=,iv:4neE9r069vFa9CotaB0bTPrNHa6IlUVqE/AnLRNuZMg=,tag:sImyDCLu72+JqE9KP6K5TA==,type:str]
    version: 3.13.0
